### PR TITLE
DCS: Feature/limit dcs scans to one at a time

### LINKED ISSUE #1094: [TASK] DCS: Limit scans to one at a time to prevent NL messages overrun
## Description

When a scan is triggered on the 2 radios at the same time - the events of dump_results may overlap and the NL buffer size may exceed the expected size due to messages overlap (as described in #1001 )
The DCS can protect against simultaneous scans and prevent the issue from happening.
Moreover, the crash of the monitor thread in the case of one event-message-overlap is too strict since we see that the following events arrive successfully.

The root cause of the issue might be DWPAL implementation - and since we plan to move the monitor thread to use the mon_wlan_hal_nl80211 instead of DWPAL, and since there is no requirement to support scan on both radios simultaneously, the decision is to limit the DCS feature to scan one radio at a time.

As part of simulating the issue, we found that although the DCS task handles a scan-triggered event timeout, it should also handle a scan-trigger-response returning an error (which also can arrive much earlier than the timeout itself)

Fixes: #1001 

## Exit criteria

- [x] a single wrong-buffer-size as described in #1001 should not cause monitor thread crash
PR: #1100 
- [x] DCS task should handle scan-trigger-response with error
will be handled as part of #1135 
- [x] limit DCS tasks to a single scan on all radios at a time
PR: #1134 

## Detailed description

Currently, DCS tasks do not share resources and are completely independent. The solution suggested is for all DCS tasks to share a common "is-scan-in-progress" in the DB which that each task must check before starting a new scan.
Multi-threading must be taken into account in the solution provided.

### PR DESCRIPTION
**Pull request by adam1985d**
Added `FINISH` state and moved the scan-cleanups to the `FINISH` state.

Added to the DCS class functions and a static data member that adds the capability to limit to a single scan at a time.
Added PRE_SCAN state in which the limitation of single-scan-at-a-time is enforced. When single-scan or continuous-scan conditions are met, the state is changed to PRE_SCAN and only when the no-scan-in-progress condition is met, the state is changed to `TRIGGER_SCAN` which triggers the scan.

The limit to a single scan at a time is independent of the number of DCS tasks created.

The tasks release the ownership of the scan in the new `FINISH` state as part of the scan-cleanup.

In the case that the DCS task performs a retry of the scan, the task will require to take ownership once again - this is to prevent starvation of other tasks.

Fixes: #1094

### CODE REVIEW

File: controller/src/beerocks/master/tasks/dynamic_channel_selection_task.h [hunk 1]
```diff
@@ -90,6 +91,8 @@ class dynamic_channel_selection_task : public task, public std::enable_shared_fr
 
     bool m_is_single_scan_pending = false;
     bool m_is_single_scan         = false;
+
+    static int m_scanning;
```
Comment (tomereli) [inline controller/src/beerocks/master/tasks/dynamic_channel_selection_task.h]:
```suggestion
    static int m_scanning_task_id = -1; // Currently scanning task id. -1 means no scan in progress.
```

File: controller/src/beerocks/master/tasks/dynamic_channel_selection_task.h [hunk 2]
```diff
@@ -20,6 +20,7 @@
 // Helper MACROs for Enum/String generation
 #define GENERATE_ENUM(ENUM) ENUM,
 #define GENERATE_STRING(STRING) #STRING,
+#define NO_SCAN_IN_PROGRESS -1
```
Comment (tomereli) [inline controller/src/beerocks/master/tasks/dynamic_channel_selection_task.h]: If you change `m_scanning` to `m_scanning_task_id`, no need for this define.

File: controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp [hunk 3]
```diff
@@ -206,6 +224,13 @@ void dynamic_channel_selection_task::work()
     case eState::ABORT_SCAN: {
         LOG(ERROR) << "aborting scan for mac=" << m_radio_mac << ", last_scan_timestamp is not set";
 
+        if (m_scanning != id) {
+            TASK_LOG(ERROR) << "scan abort event received for a task that isn't the scanning task";
+        } else {
+            // scan by current task is aborted
+            m_scanning = NO_SCAN_IN_PROGRESS;
```
Comment (tomereli) [inline controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp]:
```suggestion
            m_scanning_task_id = -1;
```

File: controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp [hunk 4]
```diff
@@ -206,6 +224,13 @@ void dynamic_channel_selection_task::work()
     case eState::ABORT_SCAN: {
         LOG(ERROR) << "aborting scan for mac=" << m_radio_mac << ", last_scan_timestamp is not set";
 
+        if (m_scanning != id) {
```
Comment (tomereli) [inline controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp]:
```suggestion
        if (m_scanning_task_id != id) {
```

File: controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp [hunk 5]
```diff
@@ -187,6 +195,16 @@ void dynamic_channel_selection_task::work()
...
+            TASK_LOG(ERROR) << "scan done event received for a task that isn't the scanning task";
+            m_last_scan_error_code = beerocks::eChannelScanErrCode::CHANNEL_SCAN_INTERNAL_FAILURE;
+            fsm_move_state(eState::ABORT_SCAN);
+            break;
+        }
+
+        // scan by current task is complete
+        m_scanning = NO_SCAN_IN_PROGRESS;
```
Comment (tomereli) [inline controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp]:
```suggestion
        m_scanning_task_id = -1; //mark no task is currently scanning
```

File: controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp [hunk 6]
```diff
@@ -118,6 +120,12 @@ void dynamic_channel_selection_task::work()
         break;
     }
     case eState::TRIGGER_SCAN: {
+        if (m_scanning != NO_SCAN_IN_PROGRESS) {
+            break;
+        }
+        // set scanning task id to current task id
+        m_scanning = id;
```
Comment (tomereli) [inline controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp]:
```suggestion
        m_scanning_task_id = id;
```

File: controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp [hunk 7]
```diff
@@ -18,6 +18,8 @@
 std::string s_ar_states[] = {FOREACH_DCS_STATE(GENERATE_STRING)};
 std::string s_ar_events[] = {FOREACH_DCS_EVENT(GENERATE_STRING)};
 
+int dynamic_channel_selection_task::m_scanning = NO_SCAN_IN_PROGRESS;
```
Comment (tomereli) [inline controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp]:
```suggestion
int dynamic_channel_selection_task::m_scanning = -1; //no scan in progress
```

**Review by tomereli — APPROVED** [review]
Small changes which I think you should do, but nothing that requires re-review.

File: controller/src/beerocks/master/tasks/dynamic_channel_selection_task.h (hunk 1 above)
Comment (vitalybu) [inline controller/src/beerocks/master/tasks/dynamic_channel_selection_task.h]:
```suggestion
    static int m_scanning_task_id;
```

Comment (adam1985d) [reply controller/src/beerocks/master/tasks/dynamic_channel_selection_task.h]: static initialization is done inside the cpp file. added the comment as suggested

File: controller/src/beerocks/master/tasks/dynamic_channel_selection_task.h (hunk 2 above)
Comment (vitalybu) [inline controller/src/beerocks/master/tasks/dynamic_channel_selection_task.h]: No need for this define, we use `-1` for invalid task id.
Maybe should add an `INVALID_TASK_ID` to the base class (but it's not part of this PR anyway).

File: controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp [hunk 8]
```diff
@@ -118,6 +120,12 @@ void dynamic_channel_selection_task::work()
         break;
     }
     case eState::TRIGGER_SCAN: {
+        if (m_scanning != NO_SCAN_IN_PROGRESS) {
```
Comment (vitalybu) [inline controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp]: When moving to the `TRIGGER_SCAN` state from the `IDLE` state, we also initialize the `m_last_scan_try_timestamp` member. If now the task will block until the previous scan is complete, what impact does it have on this timeout?
Maybe it's better to remain in `IDLE` state? or even in `INIT`?

**Review by vitalybu — CHANGES_REQUESTED** [review]

File: controller/src/beerocks/master/tasks/dynamic_channel_selection_task.h (hunk 2 above)
Comment (adam1985d) [reply controller/src/beerocks/master/tasks/dynamic_channel_selection_task.h]: changed `m_scanning` to `m_scanning_task_id`

File: controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp (hunk 3 above)
Comment (adam1985d) [reply controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp]: done

File: controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp (hunk 4 above)
Comment (adam1985d) [reply controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp]: done

File: controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp (hunk 6 above)
Comment (adam1985d) [reply controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp]: done

File: controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp (hunk 7 above)
Comment (adam1985d) [reply controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp]: done

File: controller/src/beerocks/master/tasks/dynamic_channel_selection_task.h (hunk 1 above)
Comment (adam1985d) [reply controller/src/beerocks/master/tasks/dynamic_channel_selection_task.h]: done

File: controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp (hunk 8 above)
Comment (adam1985d) [reply controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp]: good point, but I think it is better to move the `m_last_scan_try_timestamp` set point to where we actually trigger the scan - meaning the `TRIGGER_SCAN` state.
will move the set of `m_last_scan_try_timestamp` to `TRIGGER_SCAN` state - right after setting the `m_scanning_task_id`

File: controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp [hunk 9]
```diff
@@ -108,23 +108,22 @@ void dynamic_channel_selection_task::work()
             LOG(DEBUG) << "single scan is pending, trigger single scan";
             fsm_move_state(eState::TRIGGER_SCAN);
         } else if (database.get_channel_scan_is_enabled(m_radio_mac)) {
-            auto now = std::chrono::steady_clock::now();
-
-            if (now > m_next_scan_timestamp_interval) {
+            if (std::chrono::steady_clock::now() > m_next_scan_timestamp_interval) {
```
Comment (vitalybu) [inline controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp:112]: I still think that there's no sense to move into the `TRIGGER_SCAN` state if you can't really trigger a scan.
The task should remain in `IDLE` until it's able to trigger a scan.

File: controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp [hunk 10]
```diff
@@ -195,15 +194,15 @@ void dynamic_channel_selection_task::work()
     case eState::SCAN_DONE: {
         LOG(TRACE) << "SCAN_DONE";
 
-        if (m_scanning != id) {
+        if (m_scanning_task_id != id) {
             TASK_LOG(ERROR) << "scan done event received for a task that isn't the scanning task";
             m_last_scan_error_code = beerocks::eChannelScanErrCode::CHANNEL_SCAN_INTERNAL_FAILURE;
             fsm_move_state(eState::ABORT_SCAN);
```
Comment (vitalybu) [inline controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp]: Why do we `ABORT` the scan in this case? How can this even happen?

File: controller/src/beerocks/master/tasks/dynamic_channel_selection_task.h (hunk 2 above)
Comment (adam1985d) [reply controller/src/beerocks/master/tasks/dynamic_channel_selection_task.h]: removed the define

**Review by vitalybu — CHANGES_REQUESTED** [review]

File: controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp (hunk 9 above)
Comment (adam1985d) [reply controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp:112]: please see the last fixup - it addresses both.
I will edit the commit message accordingly as part of the squash

File: controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp [hunk 11]
```diff
@@ -457,4 +447,25 @@ void dynamic_channel_selection_task::fsm_move_state(eState new_state)
...
+bool dynamic_channel_selection_task::finish_scan()
+{
+    if (m_scanning_task_id != id) {
+        TASK_LOG(ERROR) << "finish scan is called for a task that isn't the scanning task";
+        return false;
+    }
+    // scan by current task is aborted
+    m_scanning_task_id = -1;
+    return true;
+}
```
Comment (vitalybu) [inline controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp]: Missing new line

File: controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp [hunk 12]
```diff
@@ -194,16 +190,13 @@ void dynamic_channel_selection_task::work()
     case eState::SCAN_DONE: {
         LOG(TRACE) << "SCAN_DONE";
 
-        if (m_scanning_task_id != id) {
+        if (!finish_scan()) {
```
Comment (vitalybu) [inline controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp]: A better solution may be to add a new `FINISH` state, where you finalize everything.
Then you won't have to do this from multiple states.

File: controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp [hunk 13]
```diff
@@ -102,28 +102,24 @@ void dynamic_channel_selection_task::work()
         break;
     }
     case eState::IDLE: {
-        if (m_is_single_scan_pending) {
+        if (m_is_single_scan_pending && start_scan()) {
```
Comment (vitalybu) [inline controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp]: IMO It's better to call this function right before moving to the `TRIGGER_SCAN` state.
Something like this:
```c++
auto now = std::chrono::steady_clock::now();
if (m_is_single_scan_pending) {
    ...
} else if (database.get_channel_scan_is_enabled(m_radio_mac) {
    ...
} else {
    break;
}

if (start_scan()) {
    m_last_scan_try_timestamp = now;
    fsm_move_state(eState::TRIGGER_SCAN);
}
```

In this case you actually start the scan (`start_scan()`) only when all conditions are met and no other task is currently scanning.

**Review by vitalybu — CHANGES_REQUESTED** [review]

File: controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp (hunk 11 above)
Comment (adam1985d) [reply controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp]: true - I intend to run the clang after the squash

File: controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp (hunk 13 above)
Comment (adam1985d) [reply controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp]: but the solution you suggest updates the `m_last_scan_try_timestamp` for a single scan as well.
also, you don't want to set the data members only to then break due to start_scan() returning false

File: controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp (hunk 10 above)
Comment (adam1985d) [reply controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp]: it shouldn't happen - but wanted to be extra safe here and not update the `m_scanning_task_id` and the results if for some reason this state is reached even though we don't own the scanning-permission

File: controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp (hunk 13 above)
Comment (vitalybu) [reply controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp]: Also true, but can be solved by adding another state :)
`IDLE` -> `CAN_SCAN` -> `TRIGGER_SCAN` -> ... -> `FINISH`

The FSM will reach the `CAN_SCAN` state only when it's ready to scan.
It'll wait in this state until it can actually trigger a scan, and only then move to `TRIGGER_SCAN`.
`FINISH` will always do all the cleanups (including removing the id of the scanning task).

File: controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp (hunk 12 above)
Comment (adam1985d) [reply controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp]: I agree - but this is more of refactoring the scan_done and abort_scan cleanups to be in a new state - and less of the actual add of protection.

I added this as part of the PR.

File: controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp (hunk 13 above)
Comment (adam1985d) [reply controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp]: it is more of `SHOULD_SCAN` rather than `CAN_SCAN` since the `start_scan()` itself is the condition of can-scan

File: controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp (hunk 12 above)
Comment (kantera800) [reply controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp]: good idea, steering task also use such a state

File: controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp (hunk 8 above)
Comment (adam1985d) [reply controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp]: please re-review. provided a solution that is based on your suggestion.

File: controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp (hunk 13 above)
Comment (adam1985d) [reply controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp]: I added a PRE_SCAN state and FINISH state - please re-review

File: controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp [hunk 14]
```diff
@@ -432,4 +449,25 @@ void dynamic_channel_selection_task::fsm_move_state(eState new_state)
...
+}
+
+bool dynamic_channel_selection_task::finish_scan()
+{
+    if (m_scanning_task_id != id) {
+        TASK_LOG(ERROR) << "finish scan is called for a task that isn't the scanning task";
+        return false;
+    }
+    // scan by current task is aborted
+    m_scanning_task_id = -1;
```
Comment (kantera800) [inline controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp:476]: I'm pretty sure that a task can be erased without going through finish_scan().
I'm wondering if this is the only place for clearing this flag.

maybe we should clear it in the destructor
` ~dynamic_channel_selection_task() { m_scanning_task_id = -1 }`

or 

```
void dynamic_channel_selection_task::handle_task_end()
{
  m_scanning_task_id = -1;
}
```

File: controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp [hunk 15]
```diff
@@ -103,19 +106,28 @@ void dynamic_channel_selection_task::work()
         if (m_is_single_scan_pending) {
             m_is_single_scan         = true;
             m_is_single_scan_pending = false;
```
Comment (kantera800) [inline controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp:108]: (nitpick ) I know its not part of this PR but `m_is_single_scan_pending` and `m_is_single_scan_pending` confused me .
i prefer `m_is_manual_scan` and also would add a comment in code why do we need to treat manual scan differently from continues one .

File: controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp (hunk 14 above)
Comment (vitalybu) [reply controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp:476]: That's a good point, but instead of setting `m_scanning_task_id = -1;`, you should just call `finish_scan();` from the destructor (as it also make checks that the current task if the owner of this flag).

File: controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp (hunk 15 above)
Comment (adam1985d) [reply controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp:108]: will add it as a separate hotfix, but for discussion, we use the "single" terminology across the entire DCS feature implementation - why should the task name it differently?
we can change it to `m_handling_single_scan_request` if it would be more clear.

secondly - the `m_is_single_scan_pending` is a flag that indicates that a single scan request was made and haven't been treated yet.
the `m_is_single_scan` is used through the entire task to determine which scan params to read and which scan results to update. where do you think a comment regarding this should be added?

File: controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp (hunk 14 above)
Comment (adam1985d) [reply controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp:476]: added a fixup commit that calls `finish_scan();` as part of the DTOR

File: controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp (hunk 15 above)
Comment (kantera800) [reply controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp:108]: > will add it as a separate hotfix, but for discussion, we use the "single" terminology across the entire DCS feature implementation - why should the task name it differently?
> we can change it to `m_handling_single_scan_request` if it would be more clear.
>
In that case just adding "request" would do 
`m_single_scan_request` 
`m_single_scan_request_pending`

> 
> secondly - the `m_is_single_scan_pending` is a flag that indicates that a single scan request was made and haven't been treated yet.
> the `m_is_single_scan` is used through the entire task to determine which scan params to read and which scan results to update. where do you think a comment regarding this should be added?

i would add it to the header file

**Review by kantera800 — APPROVED** [review]

File: controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp [hunk 16]
```diff
@@ -432,4 +449,25 @@ void dynamic_channel_selection_task::fsm_move_state(eState new_state)
...
+        return false;
+    }
+    // set scanning task id to current task id
+    m_scanning_task_id = id;
+    return true;
+}
+
+bool dynamic_channel_selection_task::finish_scan()
+{
+    if (m_scanning_task_id != id) {
```
Comment (vitalybu) [inline controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp:470]: Since now you're also calling this method from the destructor, you should also check that `m_scanning_task_id != -1`, otherwise it will always be printed:
```suggestion
    if (m_scanning_task_id != -1 && m_scanning_task_id != id) {
```

File: controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp (hunk 11 above)
Comment (vitalybu) [reply controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp]: Still missing

File: controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp [hunk 17]
```diff
@@ -432,4 +449,25 @@ void dynamic_channel_selection_task::fsm_move_state(eState new_state)
...
+        TASK_LOG(ERROR) << "finish scan is called for a task that isn't the scanning task";
+        return false;
+    }
+    // scan by current task is aborted
```
Comment (vitalybu) [inline controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp]:
```suggestion
    
    // scan by current task is finished
```

File: controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp (hunk 16 above)
Comment (adam1985d) [reply controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp:470]: I will add a separate check:
```
if (m_scanning_task_id == -1) {
    return true;
}
```

File: controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp (hunk 17 above)
Comment (adam1985d) [reply controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp]: fixed

File: controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp (hunk 11 above)
Comment (adam1985d) [reply controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp]: fixed

**Review by vitalybu — APPROVED** [review]
