### PR TITLE
Bugfix/channel switch wrong bandwidth

### LINKED ISSUE #344: [TASK] Pass flow 4.2.1 test in testbed
# Description

Perform all steps necessary to pass the test associated with flow 4.2.1 in the certification testbed.

# Exit criteria

- Turris Omnia OpenWrt with firmware master branch
- Certification test passes
- Test results uploaded to https://ftp.essensium.com/owncloud/index.php/s/ketl3eFhIgwcweZ

### LINKED ISSUE #345: 4.2.1 Multi-AP Ethernet Onboarding and Initialization
The prplMesh agent on Turris Omnia with OpenWrt needs to pass the certification test case 4.2.1 as defined by the Wi-Fi CERTIFIED EasyMesh (tm) Test Plan.

- [x] #336 Support wfa_ca in agent
- [x] #346 AP configuration on Turris Omnia / RAX40 OpenWrt
- [x] #343 Test flow for 4.2.1 Multi-AP Ethernet Onboarding and Initialization
- [x] #344 Pass flow 4.2.1 test in testbed

### PR DESCRIPTION
**Pull request by tomereli**
Fix several bugs in the channel selection implementation:
- Fix wrong bandwidth use in DWPAL which caused chan_switch command to fail
- Fix bug in agent's channel selection which selected a restricted channel
- Fix bug in agent's channel selection which caused the agent not to send operating channel report when channel switch was not needed.
- Fix bug in agent's channel selection which did not follow the Multi-AP specification by not marking channel preference with empty channel list as non-operable

WiFi Alliance support case # 00129476 helped identify the final bug. With this, we pass 4.2.1 without any workarounds.

Fixes #344

### CODE REVIEW

**Comment by YuriyMasechko** [comment]
According to design channel selection request should contain only restricted channels. But it still could contain empty list and we should count this. So pls skip operating classes with empty list and don't add  them to preferences.

File: agent/src/beerocks/slave/son_slave_thread.cpp [hunk 1]
```diff
@@ -4555,9 +4555,13 @@ bool slave_thread::handle_channel_selection_request(Socket *sd, ieee1905_1::Cmdu
         return false;
     }
 
-    if (!switch_required && !power_limit_received) {
+    if (!switch_required) {
+        LOG(INFO) << "Channel switch not required, sending operating channel report";
         send_operating_channel_report();
```
Comment (YuriyMasechko) [inline agent/src/beerocks/slave/son_slave_thread.cpp:4616]: Is this temporary solution? If power limit was received, channel report should contain new power limit.

Comment (tomereli) [reply agent/src/beerocks/slave/son_slave_thread.cpp]: Good point, will fix it.

**Comment by tomereli** [comment]
> According to design channel selection request should contain only restricted channels. But it still could contain empty list and we should count this. So pls skip operating classes with empty list and don't add them to preferences.

See https://github.com/prplfoundation/prplMesh/pull/899/commits/566198a812c7d30a359cca5f894a08eb4c3d8e76

File: agent/src/beerocks/slave/son_slave_thread.cpp [hunk 2]
```diff
@@ -4475,37 +4475,50 @@ bool slave_thread::handle_channel_selection_request(Socket *sd, ieee1905_1::Cmdu
                          });
 
         if (is_restricted != preference.channels.end()) {
+            LOG(INFO) << "Current channel " << int(hostap_cs_params.channel)
+                      << " is restricted, switch required";
             switch_required = 1;
```
Comment (morantr) [inline agent/src/beerocks/slave/son_slave_thread.cpp]: Why `switch_required` is defined as `int`? Clearly it should be `bool` and be set to `true` or `false` instead of `1` or `0`.

File: agent/src/beerocks/slave/son_slave_thread.cpp [hunk 3]
```diff
@@ -4475,37 +4475,50 @@ bool slave_thread::handle_channel_selection_request(Socket *sd, ieee1905_1::Cmdu
...
-                                    (beerocks::eWiFiBandwidth)hostap_params.supported_channels[i]
-                                        .channel_bandwidth) &&
-                            hostap_params.supported_channels[i].channel == wifi_channel.channel);
-                    });
-
-                if (is_restricted == preference.channels.end() &&
-                    !hostap_params.supported_channels[i].is_dfs_channel) {
-                    channel_to_switch = hostap_params.supported_channels[i];
-                    break;
+        for (auto preference : channel_preferences) {
```
Comment (morantr) [inline agent/src/beerocks/slave/son_slave_thread.cpp]: It needs to be const reference.

File: agent/src/beerocks/slave/son_slave_thread.cpp (hunk 1 above)
Comment (tomereli) [reply agent/src/beerocks/slave/son_slave_thread.cpp:4616]: Yes this is a temporary solution so we can pass certification. I added a comment and a TODO message linking this to https://github.com/prplfoundation/prplMesh/issues/725

File: agent/src/beerocks/slave/son_slave_thread.cpp [hunk 4]
```diff
@@ -4475,37 +4475,50 @@ bool slave_thread::handle_channel_selection_request(Socket *sd, ieee1905_1::Cmdu
                          });
```
Comment (morantr) [inline agent/src/beerocks/slave/son_slave_thread.cpp]: I don't understand why we set `is_restricted` if the channel from the list is equal to the current channel.
AFAIR it is only restricted if the channel preference is 0.
So IMO it should be looking like this:
```cpp
    for (const auto &preference : channel_preferences) {
        // Check if channel list is with preference of restricted channel
        if (preference.preference.preference == 0) {
            continue;
        }

        auto current_channel_is_restricted = preference.channels.end() == 
                std::find_if(preference.channels.begin(), preference.channels.end(),
                [&hostap_cs_params.channel](const beerocks::message::sWifiChannel &wifi_channel) {
	              return hostap_cs_params.channel == wifi_channel.channel;
	        );

        if (current_channel_is_restricted) {
            LOG(INFO) << "Current channel " << int(hostap_cs_params.channel)
                      << " is restricted, switch required";
            switch_required = true;
            break;
        }
    }
```

Please notice that on my code suggestion, I changed a few things:
1. Use const reference on the main for-loop.
2. Add only `hostap_cs_params.channe` as reference to the lambda function. Adding everything as a reference is useless and it is translated to passing everything possible as a reference to the function, so it hurts performance.
3. Added a `break` when `switch_required` is set to `true`. There is no need to continue with furthermore iterations. 

I'm not sure, but it seems to me that it is possible to merge this loop and the one down below.

**Comment by tomereli** [comment]
> Don't you always need to send the operating channel report, regardless of whether the switch is required?

Yes I do, and I updated the PR to do that. With this we pass the test.

**Review by morantr — COMMENTED** [review]
I didn't finish, this is what I got so far.

File: agent/src/beerocks/slave/son_slave_thread.cpp (hunk 2 above)
Comment (tomereli) [reply agent/src/beerocks/slave/son_slave_thread.cpp]: Correct, but it was int to begin with so I didn't want to change that.
If you think it is critical (you didn't mark this as (nitpick), I can add another commit which does that.

File: agent/src/beerocks/slave/son_slave_thread.cpp (hunk 3 above)
Comment (tomereli) [reply agent/src/beerocks/slave/son_slave_thread.cpp]: Correct but again this was the same in previous implementation. Will change as part of a separate commit.

File: agent/src/beerocks/slave/son_slave_thread.cpp (hunk 4 above)
Comment (tomereli) [reply agent/src/beerocks/slave/son_slave_thread.cpp]: You are again correct. The current code assumes that `preference` is always `0`, meaning always non-operable. The correct solution is to take the actual preference into account but then we will need to add much more code which is not related to this PR and should be handled in #725 - this I prefer not to do as part of a bug fix PR.

Regarding the change it self - yours is wrong, since if channel list is empty, you don't mark *any* channel as non-operable (restricted). 

However thank you for this comment - I fixed everything you requested.

File: agent/src/beerocks/slave/son_slave_thread.cpp (hunk 2 above)
Comment (tomereli) [reply agent/src/beerocks/slave/son_slave_thread.cpp]: NVM apparently I already changed this as part of c7b5669

File: agent/src/beerocks/slave/son_slave_thread.cpp (hunk 3 above)
Comment (tomereli) [reply agent/src/beerocks/slave/son_slave_thread.cpp]: fixed

**Comment by tomereli** [comment]
[4.2.1_PASS.zip](https://github.com/prplfoundation/prplMesh/files/4281488/4.2.1_PASS.zip)

File: agent/src/beerocks/slave/son_slave_thread.cpp (hunk 4 above)
Comment (morantr) [reply agent/src/beerocks/slave/son_slave_thread.cpp]: Just to clarify, this comment was on the upper for-loop (line 4470)and not the one you have changed.

Comment (rmelotte) [reply agent/src/beerocks/slave/son_slave_thread.cpp]: Just a quick note because I've seen it before, this is not correct:
> Adding everything as a reference is useless and it is translated to passing everything possible as a reference to the function"

Only the variables you use in the lambda body will be captured by reference so you don't need to explicitly list them (see [cppreference](https://en.cppreference.com/w/cpp/language/lambda)). 
Of course you can still list them if you prefer but if it's for "performance reasons", then you don't have to. The 2 are equivalent.

File: agent/src/beerocks/slave/son_slave_thread.cpp [hunk 5]
```diff
@@ -4422,29 +4422,37 @@ beerocks::message::sWifiChannel slave_thread::channel_selection_select_channel()
...
 {
-    for (auto preference : channel_preferences) {
+    auto channel         = hostap_cs_params.channel;
+    auto bw              = static_cast<beerocks::eWiFiBandwidth>(hostap_cs_params.bandwidth);
+    auto operating_class = wireless_utils::get_operating_class_by_channel(channel, bw);
+
+    for (const auto &preference : channel_preferences) {
+        // for now we handle only non-operable preference
+        // TODO - handle as part of https://github.com/prplfoundation/prplMesh/issues/725
+        if (preference.preference.preference != 0) {
```
Comment (mariomaz) [inline agent/src/beerocks/slave/son_slave_thread.cpp]: Define an enum instead of using a magic number (i.e.: NON_OPERABLE: 0, MOST_PREFERRED: 15)
(nitpick)

Comment (mariomaz) [inline agent/src/beerocks/slave/son_slave_thread.cpp]: Surely there must be a better name for this: `preference.preference.preference`
(nitpick)

File: agent/src/beerocks/slave/son_slave_thread.cpp [hunk 6]
```diff
@@ -4382,16 +4382,66 @@ bool slave_thread::handle_channel_preference_query(Socket *sd, ieee1905_1::CmduM
     return message_com::send_cmdu(ap_manager_socket, cmdu_tx);
 }
 
-bool slave_thread::handle_channel_selection_request(Socket *sd, ieee1905_1::CmduMessageRx &cmdu_rx)
+beerocks::message::sWifiChannel slave_thread::channel_selection_select_channel()
 {
-    const auto mid = cmdu_rx.getMessageId();
-    LOG(DEBUG) << "Received CHANNEL_SELECTION_REQUEST_MESSAGE, mid=" << std::dec << int(mid);
+    for (auto preference : channel_preferences) {
```
Comment (morantr) [inline agent/src/beerocks/slave/son_slave_thread.cpp]: const reference

File: agent/src/beerocks/slave/son_slave_thread.cpp [hunk 7]
```diff
@@ -4382,16 +4382,66 @@ bool slave_thread::handle_channel_preference_query(Socket *sd, ieee1905_1::CmduM
...
-    int switch_required       = 0;
-    int power_limit           = 0;
-    beerocks::message::sWifiChannel channel_to_switch;
+    LOG(ERROR) << "Could not find a suitable channel";
+    return beerocks::message::sWifiChannel();
+}
+
+bool slave_thread::channel_selection_current_channel_restricted()
+{
+    for (auto preference : channel_preferences) {
```
Comment (morantr) [inline agent/src/beerocks/slave/son_slave_thread.cpp]: const reference

File: agent/src/beerocks/slave/son_slave_thread.cpp [hunk 8]
```diff
@@ -4448,6 +4498,12 @@ bool slave_thread::handle_channel_selection_request(Socket *sd, ieee1905_1::Cmdu
         }
     }
 
+    return true;
+}
+
+bool slave_thread::channel_selection_get_transmit_power_limit(ieee1905_1::CmduMessageRx &cmdu_rx,
+                                                              int &power_limit)
+{
     for (auto tx_power_limit_tlv : cmdu_rx.getClassList<wfa_map::tlvTransmitPowerLimit>()) {
```
Comment (mariomaz) [inline agent/src/beerocks/slave/son_slave_thread.cpp]: You should use 'const auto&'
I think `cmdu_rx` parameter should also be a const reference

File: agent/src/beerocks/slave/son_slave_thread.cpp [hunk 9]
```diff
@@ -4382,16 +4382,66 @@ bool slave_thread::handle_channel_preference_query(Socket *sd, ieee1905_1::CmduM
...
+    LOG(INFO) << "Current channel " << int(hostap_cs_params.channel)
+              << " not restricted, channel switch not required";
+    return false;
+}
+
+bool slave_thread::channel_selection_get_channel_preference(ieee1905_1::CmduMessageRx &cmdu_rx)
+{
     channel_preferences.clear();
 
     for (auto channel_preference_tlv : cmdu_rx.getClassList<wfa_map::tlvChannelPreference>()) {
```
Comment (mariomaz) [inline agent/src/beerocks/slave/son_slave_thread.cpp:4467]: You should use 'const auto&'
I think `cmdu_rx` parameter should also be a const reference

**Review by mariomaz — CHANGES_REQUESTED** [review]

File: agent/src/beerocks/slave/son_slave_thread.cpp (hunk 5 above)
Comment (morantr) [reply agent/src/beerocks/slave/son_slave_thread.cpp]: It bothers me too.

**Review by morantr — CHANGES_REQUESTED** [review]

**Review by morantr — APPROVED** [review]

File: agent/src/beerocks/slave/son_slave_thread.cpp (hunk 5 above)
Comment (tomereli) [reply agent/src/beerocks/slave/son_slave_thread.cpp]: Done

Comment (tomereli) [reply agent/src/beerocks/slave/son_slave_thread.cpp]: Not part of this PR, but I can fix it in a separate commit. Will do.

File: agent/src/beerocks/slave/son_slave_thread.cpp (hunk 8 above)
Comment (tomereli) [reply agent/src/beerocks/slave/son_slave_thread.cpp]: Done

File: agent/src/beerocks/slave/son_slave_thread.cpp (hunk 9 above)
Comment (mariomaz) [reply agent/src/beerocks/slave/son_slave_thread.cpp:4467]: This one has been marked as resolved but it is not.
This file deserves a full review regarding the 'const auto&' usage.

**Review by mariomaz — APPROVED** [review]
son_slave_thread.cpp deserves a full review regarding the 'const auto&' usage.
