### PR TITLE
agent: channel_sel: ignore channels from other operating classes

### LINKED ISSUE #960: [BUG] agent: MAP-4.2.1 fails with "No Operating Channel Report message found"
Job: https://gitlab.com/prpl-foundation/prplMesh/-/jobs/468547961

logs: https://gitlab.com/prpl-foundation/prplMesh/-/jobs/468547961/artifacts/browse/logs/FAIL/MAP-4.2.1/

### PR DESCRIPTION
**Pull request by tomereli**
There is a bug in the current channel selection implementation which was
introduced in the recent changes to channel selection.
The issue is that if the agent receives a channel selection request
with the same preference as the channel it is currently operating on,
the agent mistakingly identifies that the channel is non-operable and
therefore does not send operating channel report as it expects channel
selection to complete with CSA_Finished event.
The CSA_Finished event never arrives since no channel switch was
actually needed.

The root cause is in the get_channel_preference function when it is
called from channel_selection_current_channel_restricted() - it is
called for each channel preference before concluding that channel switch
is not required, so while the channel in question may belong to the
first preference operating class, we still continue and check the second
preference for which the channel will definitely not belong and
therefore hit be marked as non-operable.
Reproduced 100%.

The solution is to always skip channels which do not belong to the
preference operating class in channel_selection_select_channel() and in
channel_selection_current_channel_restricted(), and abort if we get non
matching channel in get_channel_preference().

Fixes #960 

Signed-off-by: Tomer Eliyahu <tomer.b.eliyahu@intel.com>

### CODE REVIEW

File: agent/src/beerocks/slave/son_slave_thread.cpp [hunk 1]
```diff
@@ -4446,10 +4448,10 @@ static uint8_t get_channel_preference(const beerocks::message::sWifiChannel chan
     auto bw                = static_cast<beerocks::eWiFiBandwidth>(channel.channel_bandwidth);
     auto operating_class   = wireless_utils::get_operating_class_by_channel(channel);
 
-    // consider channels in different operating classes as restricted
-    if (operating_class != preference.oper_class) {
-        return preference.preference;
```
Comment (arnout) [inline agent/src/beerocks/slave/son_slave_thread.cpp:4451]: This should have stayed at INOPERABLE instead of preference.preference. But asserting is fine as well.

File: agent/src/beerocks/slave/son_slave_thread.cpp [hunk 2]
```diff
@@ -4434,7 +4434,9 @@ bool slave_thread::handle_channel_preference_query(Socket *sd, ieee1905_1::CmduM
 
 /**
  * @brief Get the channel preference 
- * 
+ * Note that the channel operating class and the preference operating class has to match,
```
Comment (arnout) [inline agent/src/beerocks/slave/son_slave_thread.cpp]: (nitpick) leave an empty line before, otherwise it will be part of the 'brief'.

Maybe even better, mark is as a precondition:
```
@pre The channel operating class and the preference operating class have to match.
```

**Review by arnout — APPROVED** [review]
I can't say I fully understand the issue, but the code changes definitely seem correct.

File: agent/src/beerocks/slave/son_slave_thread.cpp [hunk 3]
```diff
@@ -4446,10 +4448,10 @@ static uint8_t get_channel_preference(const beerocks::message::sWifiChannel chan
     auto bw                = static_cast<beerocks::eWiFiBandwidth>(channel.channel_bandwidth);
     auto operating_class   = wireless_utils::get_operating_class_by_channel(channel);
 
-    // consider channels in different operating classes as restricted
-    if (operating_class != preference.oper_class) {
-        return preference.preference;
-    }
+    LOG_IF(operating_class != preference.oper_class, FATAL)
```
Comment (mariomaz) [inline agent/src/beerocks/slave/son_slave_thread.cpp:4450]: Shall this really abort execution if it does ever happen? Or should it be treated as an error and ignored?

**Review by mariomaz — COMMENTED** [review]
I don't either fully understand the issue here but changes look good so I approve it.
This is a method for which we could have easily created a unit-test

File: agent/src/beerocks/slave/son_slave_thread.cpp (hunk 3 above)
Comment (tomereli) [reply agent/src/beerocks/slave/son_slave_thread.cpp:4450]: This will result with `abort()`.

**Review by mariomaz — APPROVED** [review]
Approving
