### PR TITLE
[BUG] agent: Channel selection request should yield a single channel selection response

### LINKED ISSUE #367: [TASK] Pass flow 4.5.2 test in testbed
# Description

Perform all steps necessary to pass the test associated with flow 4.5.2 in the certification testbed.

# Exit criteria

- Turris Omnia OpenWrt with firmware master branch
- Certification test passes with all configurations
- Test results uploaded to https://ftp.essensium.com/owncloud/index.php/s/ketl3eFhIgwcweZ

### LINKED ISSUE #368: 4.5.2 Channel Selection Request Message
The prplMesh agent on Turris Omnia with OpenWrt needs to pass the certification test case 4.5.2 as defined by the Wi-Fi CERTIFIED EasyMesh (tm) Test Plan.

- [x] #366 Channel selection for nl80211
- [x] #725 Perform channel selection
- [x] #369 Implement Operating Channel Report for nl80211
- [ ] #367 Pass flow 4.5.2 test in testbed

### LINKED ISSUE #1364: [BUG] agent: Channel selection request should yield a single channel selection response
The channel selection request is forwarded to all slaves, and each slave handles it individually. As a result, each slave sends a response with a channel selection response TLV with that radio's MAC address. Since all of the responses have the same MID, only one of them actually gets sent on the network, the rest is filtered out by the transport's duplicate packet elimination.

This sometimes (often, actually) makes test 4.5.2 fail, because the packet that gets dropped is the packet that the UCC is looking for.

There are two possible solutions:
- Move the channel selection handling from son_slave to backhaul_manager. This is the step in the right direction for #1082 unified agent, but it's more work - the backhaul manager currently doesn't have any information about the current channels so that has to be added as well.
- In the son_slave, check if there is any TLV in the request targeted to that slave and ignore it if not. This is more of a workaround - it works for certification because there there is always only one radio in the channel selection request.

### PR DESCRIPTION
**Pull request by VladyslavTupikin**
Update channel selection according to the UML diagram

### CODE REVIEW

File: agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.cpp [hunk 1]
```diff
@@ -4319,6 +4328,154 @@ bool backhaul_manager::add_link_metrics(const sMacAddr &reporter_al_mac,
...
+            //        << "Failed forwarding CHANNEL_SELECTION_REQUEST_MESSAGE message to son_slave";
+            //    ret = false;
+            //    continue;
+            //}
+
+            m_channel_selection_request.push_back(mac);
+            ret = true;
+            break;
+        }
+    }
```
Comment (arnout) [inline agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.cpp]: All this is not needed, because we expect a response from *all* slaves. So what we need to do is simply to populate m_channel_selection_request with all slaves. And it has to be forwarded to the slaves, but for that we can simply return false.

File: agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.cpp [hunk 2]
```diff
@@ -4319,6 +4328,154 @@ bool backhaul_manager::add_link_metrics(const sMacAddr &reporter_al_mac,
...
+        return false;
+    }
+
+    //LOG(DEBUG) << "VT channel_selection_response->radio_uid(): "
+    //           << tlvf::mac_to_string(channel_selection_response->radio_uid());
+    //LOG(DEBUG) << "VT channel_selection_response->response_code(): "
+    //           << int(channel_selection_response->response_code());
+
+    m_channel_selection_response.push_back({channel_selection_response->radio_uid(),
+                                            uint8_t(channel_selection_response->response_code())});
```
Comment (arnout) [inline agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.cpp]: (nitpick) Thanks to @mariomaz, I discovered that we can use emplace_back instead of push_back. It avoids an additional copy.

File: agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.h [hunk 3]
```diff
@@ -552,6 +556,14 @@ class backhaul_manager : public btl::transport_socket_thread {
     std::vector<sApMetricsQuery> m_ap_metric_query;
     std::vector<sApMetricsResponse> m_ap_metric_response;
 
+    struct sChannelSelectionResponse {
+        sMacAddr radio_mac;
+        uint8_t response_code;
+    };
+
+    std::vector<sMacAddr> m_channel_selection_request;
+    std::vector<sChannelSelectionResponse> m_channel_selection_response;
```
Comment (arnout) [inline agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.h]: We should also store the MID, and check it when collecting responses.
Therefore, I think it would be nicer like this:
```suggestion
   struct sExpectedChannelSelection {
       uint16_t mid;
       std::vector<sMacAddr> requested;
       std::vector<sChannelSelectionResponse> responses;
   };
   sExpectedChannelSelection m_expected_channel_selection;
```

**Review by arnout — DISMISSED** [review]
Although the changes aren't that big, I'd like to re-review.

Also, still two things are missing:
- Final commit should have the magic message to run the 4.5.2 test.
- test_flows should be updated: there are a few TODOs in the channel selection that are now fixed.

In fact, the test flows stuff is how you should test if the issue is really fixed. So it's even better to first do the test_flows changes and then modify the code so the test passes.

File: agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.cpp (hunk 2 above)
Comment (VladyslavTupikin) [reply agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.cpp]: emphase_back does not work for the marked case.
It will be work if i add 3 useless strings for creating and filling structure elements, then structure object i will be able to put inside the vector via amphase_back

File: agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.h (hunk 3 above)
Comment (VladyslavTupikin) [reply agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.h]: Fixed.

File: agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.cpp (hunk 1 above)
Comment (VladyslavTupikin) [reply agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.cpp]: Fixed

File: agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.cpp [hunk 4]
```diff
@@ -4319,6 +4328,85 @@ bool backhaul_manager::add_link_metrics(const sMacAddr &reporter_al_mac,
...
 }
+
+bool backhaul_manager::handle_channel_selection_request(ieee1905_1::CmduMessageRx &cmdu_rx,
+                                                        const std::string &src_mac)
+{
+    const auto mid = cmdu_rx.getMessageId();
+
+    LOG(DEBUG) << "Forwarding CHANNEL_SELECTION_REQUEST to son_slave, mid=" << std::hex << int(mid);
+    m_expected_channel_selection.mid = mid;
+    for (auto &socket : slaves_sockets) {
```
Comment (mariomaz) [inline agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.cpp:4376]: If you are overwriting MID value, then I think you should first clear the list

File: agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.cpp [hunk 5]
```diff
@@ -4319,6 +4328,85 @@ bool backhaul_manager::add_link_metrics(const sMacAddr &reporter_al_mac,
...
+        m_expected_channel_selection.requests.emplace_back(socket->radio_mac);
+    }
+    // Forward to all slaves
```
Comment (mariomaz) [inline agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.cpp]: This is quite dangerous since we are handling this message by doing nothing and having faith that the default error handling will do the job for us. IIRC such default handling is going to change in a near future and this code will stop working.
Anyway, I think the comment should better explain what's going on here so maintainers can fix it if needed.

File: agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.cpp [hunk 6]
```diff
@@ -4319,6 +4328,85 @@ bool backhaul_manager::add_link_metrics(const sMacAddr &reporter_al_mac,
...
+    // We received all responses - prepare and send response message to the controller
+    auto cmdu_header =
+        cmdu_tx.create(mid, ieee1905_1::eMessageType::CHANNEL_SELECTION_RESPONSE_MESSAGE);
+
+    if (!cmdu_header) {
+        LOG(ERROR) << "Failed building IEEE1905 CHANNEL_SELECTION_RESPONSE_MESSAGE";
+        return false;
+    }
+
+    for (auto &response : m_expected_channel_selection.responses) {
```
Comment (mariomaz) [inline agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.cpp]:
```suggestion
    for (const auto &response : m_expected_channel_selection.responses) {
```

File: agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.cpp (hunk 4 above)
Comment (mariomaz) [reply agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.cpp:4376]: And also clear the list of responses

File: agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.h [hunk 7]
```diff
@@ -552,6 +556,18 @@ class backhaul_manager : public btl::transport_socket_thread {
     std::vector<sApMetricsQuery> m_ap_metric_query;
     std::vector<sApMetricsResponse> m_ap_metric_response;
 
+    struct sChannelSelectionResponse {
+        sMacAddr radio_mac;
+        uint8_t response_code;
```
Comment (mariomaz) [inline agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.h]:
```suggestion
         wfa_map::tlvChannelSelectionResponse::eResponseCode response_code;
```

With this change you save two type-casts in .cpp file

**Review by mariomaz — CHANGES_REQUESTED** [review]
Not approving because there are some changes to do

File: agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.h (hunk 7 above)
Comment (VladyslavTupikin) [reply agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.h]: fixed

File: agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.cpp (hunk 6 above)
Comment (VladyslavTupikin) [reply agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.cpp]: fixed

File: agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.cpp (hunk 5 above)
Comment (VladyslavTupikin) [reply agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.cpp]: Added advanced comment message in that place.

File: agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.cpp (hunk 4 above)
Comment (VladyslavTupikin) [reply agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.cpp:4376]: In the `handle_slave_channel_selection_response` method `requests` vector erases, then if `requests` vector empty, response message will be prepared for the controller. Before sending the response to the controller,  `responses` vector erases too.

Comment (mariomaz) [reply agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.cpp:4376]: Sorry, I didn't explain myself properly: I meant you have to consider the case when agent receives a CHANNEL_SELECTION_REQUEST **before** it has completely processed a previous one.

File: agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.cpp [hunk 8]
```diff
@@ -4319,6 +4327,89 @@ bool backhaul_manager::add_link_metrics(const sMacAddr &reporter_al_mac,
...
     return true;
 }
+
+bool backhaul_manager::handle_channel_selection_request(ieee1905_1::CmduMessageRx &cmdu_rx,
+                                                        const std::string &src_mac)
+{
+    const auto mid = cmdu_rx.getMessageId();
+
+    LOG(DEBUG) << "Forwarding CHANNEL_SELECTION_REQUEST to son_slave, mid=" << std::hex << int(mid);
+    m_expected_channel_selection.mid = mid;
```
Comment (arnout) [inline agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.cpp:4373]: As @mariomaz said, there should be something like this:

```suggestion
    // Clear previous request, if any
    m_expected_channel_selection.requests.clear();
    m_expected_channel_selection.responses.clear();
    
    m_expected_channel_selection.mid = mid;
```

Comment (VladyslavTupikin) [reply agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.cpp:4373]: added proposed fix into the code

**Review by mariomaz — APPROVED** [review]

**Review by rmelotte — APPROVED** [review]

File: agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.cpp (hunk 5 above)
Comment (arnout) [reply agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.cpp]: > This is quite dangerous since we are handling this message by doing nothing and having faith that the default error handling will do the job for us. IIRC such default handling is going to change in a near future and this code will stop working.

Yes it will change, but in the best way possible: there will be no slaves any more, so no forwarding needs to be done at all.
