### PR TITLE
Bugfix - non EasyMesh mode VAP credentials update/tear down

### LINKED ISSUE #797: [BUG] autoconfig: teardown / update VAPs in non-easymesh mode
Currently, the son slave is updating VAP credentials regardless of the operating mode.
This means that prplMesh is *always* tearing down all radios, which is fine in EasyMesh mode BUT not in a product.

BTW - I suggest renaming the "proprietary-mesh" mode to "legacy" or something like that.
We can decide whatever we want since we don't use anything other than the `Multi-AP-Controller-And-Agent` mode. 

## Steps to reproduce

Simply get to operational in UGW/RDKB.
Use hostapd_cli to see that all VAPs are in start_disabled mode, or simply read `/var/run/hostapd-phy0.conf` and see that `start_disabled=1` for all VAPs.

### PR DESCRIPTION
**Pull request by tomereli**
In EasyMesh mode, as part of autoconfiguration, the radio agent sends a
message to the AP manager to update VAP credentials which results with
an updated credentials or a full radio teardown.
In non EasyMesh mode, this should never happen - so add a check for that
and only send the message to the ap manager when in EasyMesh management
mode.

Fixes #797.

### CODE REVIEW

File: framework/platform/bpl/include/bpl/bpl_cfg.h [hunk 1]
```diff
@@ -51,6 +51,13 @@ namespace bpl {
 #define BPL_OPER_MODE_WDS_REPEATER 3
 #define BPL_OPER_MODE_L2NAT_CLIENT 4
 
+/* Platform Management Mode */
+#define BPL_MGMT_MODE_MULTIAP_CONTROLLER_AGENT 0 /* EasyMesh controller and agent */
+#define BPL_MGMT_MODE_MULTIAP_CONTROLLER 1       /* EasyMesh controller */
+#define BPL_MGMT_MODE_MULTIAP_AGENT 2            /* EasyMesh agent */
+#define BPL_MGMT_MODE_NOT_MULTIAP                                                                  \
+    3 /* Non EasyMesh /*
```
Comment (arnout) [inline framework/platform/bpl/include/bpl/bpl_cfg.h]: Why is this split over two lines?

File: framework/platform/bpl/uci/cfg/bpl_cfg.cpp [hunk 2]
```diff
@@ -34,25 +34,18 @@ int cfg_is_enabled()
...
+    case BPL_MGMT_MODE_MULTIAP_CONTROLLER_AGENT:
+        return 1;
+    case BPL_MGMT_MODE_MULTIAP_CONTROLLER:
+        return 1;
+    case BPL_MGMT_MODE_MULTIAP_AGENT:
+        return 0;
+    case BPL_MGMT_MODE_NOT_MULTIAP:
+        return (cfg_get_operating_mode() == BPL_OPER_MODE_GATEWAY) ? 1 : 0;
+    default:
+        return -1;
```
Comment (arnout) [inline framework/platform/bpl/uci/cfg/bpl_cfg.cpp:47]: I think it would be better to move this to the base class and make it non-virtual.

Oh, never mind, we don't have that for bpl...

File: framework/platform/bpl/linux/bpl_cfg.cpp [hunk 3]
```diff
@@ -83,20 +83,18 @@ int cfg_is_enabled() { return 1; }
...
+    case BPL_MGMT_MODE_MULTIAP_CONTROLLER:
+        return 1;
+    case BPL_MGMT_MODE_MULTIAP_AGENT:
         return 0;
-
-    MAPF_ERR("cfg_is_master: Unexpected management_mode " << mode_str);
-
-    return RETURN_ERR;
+    case BPL_MGMT_MODE_NOT_MULTIAP:
+        return (cfg_get_operating_mode() == BPL_OPER_MODE_GATEWAY) ? 1 : 0;
```
Comment (arnout) [inline framework/platform/bpl/linux/bpl_cfg.cpp:94]: Hm, it seems that in MULTIAP mode, the operating mode is redundant then... Actually, AFAICS, the operating mode is only used to determine if we're a gateway or not. So maybe that should be encoded here as well?

Anyway can be handled later.

File: framework/platform/bpl/include/bpl/bpl_cfg.h (hunk 1 above)
Comment (morantr) [inline framework/platform/bpl/include/bpl/bpl_cfg.h]: The last line is messed up.

File: agent/src/beerocks/slave/son_slave_thread.cpp [hunk 4]
```diff
@@ -4050,7 +4050,21 @@ bool slave_thread::handle_autoconfiguration_wsc(Socket *sd, ieee1905_1::CmduMess
         }
     }
 
-    message_com::send_cmdu(ap_manager_socket, cmdu_tx);
+    ///////////////////////////////////////////////////////////////////
+    // TODO https://github.com/prplfoundation/prplMesh/issues/797
+    //
+    // Short term solution
+    // In None EasyMesh mode, never modify hostapd configuration
```
Comment (arnout) [inline agent/src/beerocks/slave/son_slave_thread.cpp]:
```suggestion
    // In non-EasyMesh mode, never modify hostapd configuration
```

File: agent/src/beerocks/slave/son_slave_thread.cpp [hunk 5]
```diff
@@ -4050,7 +4050,21 @@ bool slave_thread::handle_autoconfiguration_wsc(Socket *sd, ieee1905_1::CmduMess
...
+    // and in this case VAPs credentials
+    //
+    // Long term solution
+    // All EasyMesh VAPs will be stored in the platform DB.
+    // All other VAPs are manual, AKA should not be modified by prplMesh
+    ////////////////////////////////////////////////////////////////////
+    if (platform_settings.management_mode != BPL_MGMT_MODE_NOT_MULTIAP) {
+        LOG(INFO) << "EasyMesh mode - really update VAP credentials";
```
Comment (arnout) [inline agent/src/beerocks/slave/son_slave_thread.cpp]: I would rather have a message in the non-EasyMesh case... And put it at WARNING level.

Ideally even only issue the message when the SSIDs are different from the already-configured SSIDs.

**Review by arnout — APPROVED** [review]

File: framework/platform/bpl/include/bpl/bpl_cfg.h [hunk 6]
```diff
@@ -51,6 +51,13 @@ namespace bpl {
 #define BPL_OPER_MODE_WDS_REPEATER 3
 #define BPL_OPER_MODE_L2NAT_CLIENT 4
 
+/* Platform Management Mode */
+#define BPL_MGMT_MODE_MULTIAP_CONTROLLER_AGENT 0 /* EasyMesh controller and agent */
+#define BPL_MGMT_MODE_MULTIAP_CONTROLLER 1       /* EasyMesh controller */
+#define BPL_MGMT_MODE_MULTIAP_AGENT 2            /* EasyMesh agent */
```
Comment (morantr) [inline framework/platform/bpl/include/bpl/bpl_cfg.h:57]: I wonder why the macro uses the term "multiap" and the comment us "eazymesh".
I think that is a good opportunity to replace it.

File: framework/platform/bpl/include/bpl/bpl_cfg.h [hunk 7]
```diff
@@ -51,6 +51,13 @@ namespace bpl {
...
+#define BPL_MGMT_MODE_NOT_MULTIAP                                                                  \
```
Comment (morantr) [inline framework/platform/bpl/include/bpl/bpl_cfg.h]: It seems weird to mee to put it in the same category of what runs on the platform because basically, the controller and the agent do run on this configuration so this is confusing a little bit.
I think it will be more suitable to give it a new category (passive mode?). But that just me, let see what others will say...

File: framework/platform/bpl/include/bpl/bpl_cfg.h (hunk 6 above)
Comment (tomereli) [reply framework/platform/bpl/include/bpl/bpl_cfg.h:57]: I would have done this as part of this change but decided not to since it will require updating prplWrt, UGW and RDKB to the new names, and will break everything until it does.
MultiAP is also correct IMO.
I can fix comment to use Multi-AP terminology.

File: framework/platform/bpl/include/bpl/bpl_cfg.h (hunk 7 above)
Comment (tomereli) [reply framework/platform/bpl/include/bpl/bpl_cfg.h]: It has to be in the same category, AKA Management mode, I don't want to introduce yet another category just for this.

File: framework/platform/bpl/include/bpl/bpl_cfg.h (hunk 1 above)
Comment (tomereli) [reply framework/platform/bpl/include/bpl/bpl_cfg.h]: because I accidentally used `/*` instead of `*/` to close the comment.. fixed.

File: framework/platform/bpl/linux/bpl_cfg.cpp (hunk 3 above)
Comment (tomereli) [reply framework/platform/bpl/linux/bpl_cfg.cpp:94]: Agree - there is a lot of redundancy here, I actually don't think we need all the modes, and indeed - it can be handled later.

File: agent/src/beerocks/slave/son_slave_thread.cpp (hunk 5 above)
Comment (tomereli) [reply agent/src/beerocks/slave/son_slave_thread.cpp]: Added a warning.

File: framework/platform/bpl/linux/bpl_cfg.cpp [hunk 8]
```diff
@@ -99,6 +99,29 @@ int cfg_is_master()
     return RETURN_ERR;
 }
 
+int cfg_get_management_mode()
+{
+    int retVal = 0;
```
Comment (vitalybu) [inline framework/platform/bpl/linux/bpl_cfg.cpp]: Shouldn't this be initialized to `-1`?
Otherwise this function will return `0 == BPL_MGMT_MODE_MULTIAP_CONTROLLER_AGENT` for an unexpected mode.
```suggestion
    int retVal = -1;
```

**Review by vitalybu — CHANGES_REQUESTED** [review]

File: framework/platform/bpl/linux/bpl_cfg.cpp (hunk 8 above)
Comment (tomereli) [reply framework/platform/bpl/linux/bpl_cfg.cpp]: Nice catch!

**Review by vitalybu — APPROVED** [review]
