### PR TITLE
Fix shellcheck errors in scripts (part 3)

### LINKED ISSUE #915: [TASK] Perform shellcheck on shell scripts
Shell scripts are risky, but the `shellcheck` tool can help to find issues with it.
- [x] (merged) Delete deprecated scripts
- [x] (**all on review**) Fix existing shellcheck issues
          (number of shellcheck issues)
   - [x] ( 1) ./ci/owncloud/upload_to_owncloud.sh
   - [x] ( 1) ./ci/run_easymesh_cert.sh
   - [x] ( 2) ./docker-builder.sh
   - [x] ( 2) ./docker-runner.sh
   - [x] ( 4) ./framework/platform/bpl/uci/scripts/platform_daemon.sh
   - [x] ( 1) ./tests/openwrt/test_status.sh
   - [x] ( 2) ./tests/test_gw_repeater.sh
   - [x] ( 6) ./tools/docker/builder/openwrt/build.sh
   - [x] ( 1) ./tools/docker/builder/rdkb/toolchain/bitbake.sh
   - [x] ( 6) ./tools/docker/build.sh
   - [x] ( 1) ./tools/docker/clang-format.sh
   - [x] (18) ./tools/docker/image-build.sh
   - [x] (10) ./tools/docker/image-pull.sh
   - [x] ( 1) ./tools/docker/runner/entrypoint.sh
   - [x] ( 3) ./tools/docker/run.sh
   - [x] ( 4) ./tools/docker/static-analysis/cppcheck.sh
   - [x] ( 2) ./tools/docker/stop.sh
   - [x] ( 7) ./tools/docker/test.sh
   - [x] ( 3) ./tools/functions.sh
   - [x] ( 2) ./tools/klocwork/kw.sh

- [x] (Canceled) Add shellcheck to the builder docker image
- [x] (**on review**) Run shellcheck in gitlab CI.

## Total lists
**Note:** Lists below will be updated based on discussion
Removal candidates:
-`./build/common/beerocks/scripts/prplmesh_utils.sh`
-`./build/install/scripts/prplmesh_utils.sh`
-`./build/out/scripts/prplmesh_utils.sh`
-`./common/beerocks/scripts/dhcp.sh`
-`./docker-builder.sh`
-`./docker-runner.sh`
-`./tests/openwrt/test_status.sh`
-`./tools/maptools.sh`
-`./tools/scripts/prplMesh-platform-init.sh`
-`./tools/commands/deploy_rdkb.sh`
-`./tools/commands/deploy_ugw.sh`
-`./framework/platform/bpl/uci/scripts/platform_daemon.sh`

No action due to soon removal:
-`./tests/test_flows.sh`
-`./tests/test_gw_repeater.sh`

Scripts not mentioned in any of lists above will be fixed.

### PR DESCRIPTION
**Pull request by MuteSpirit**
Fixing shellcheck issues in 3rd part of scripts mentioned in task #915

Description of fixed shellcheck issues you may found in commit comments

### CODE REVIEW

File: framework/platform/bpl/uci/scripts/platform_daemon.sh [hunk 1]
```diff
@@ -23,7 +23,7 @@ repeater_to_ap()
     /opt/beerocks/apm_utils.sh stop
 
     # Kill DHCP client
-    ps -A | grep [d]hcp | awk '{print $1;}' | xargs kill
+    pgrep [d]hcp | xargs kill
```
Comment (rmelotte) [inline framework/platform/bpl/uci/scripts/platform_daemon.sh:26]: This change is only possible if pgrep is available on the target platform.
Please check whether it's the case or not (@kantera800 ? @tomereli ?)

File: framework/platform/bpl/uci/scripts/platform_daemon.sh [hunk 2]
```diff
@@ -54,7 +54,7 @@ static_init()
 
     # Kill DHCP server
     echo "Kill DHCP server"
-    ps -A | grep [d]ns | awk '{print $1;}' | xargs kill
+    pgrep [d]ns | xargs kill
```
Comment (rmelotte) [inline framework/platform/bpl/uci/scripts/platform_daemon.sh:57]: Same comment, please make sure pgrep is already available on the target platform.

File: tools/docker/static-analysis/cppcheck.sh [hunk 3]
```diff
@@ -1,22 +1,14 @@
...
-    -I$rootdir/framework/common/include \
-    -I$rootdir/framework/tlvf/src/include \
-    -I$rootdir/framework/tlvf/AutoGenerated/include \
-    -I$rootdir/common/beerocks/btl/include \
-    -I$rootdir/common/beerocks/tlvf/src/include \
-    -I$rootdir/common/beerocks/tlvf/AutoGenerated/include \
-    -I$rootdir/common/beerocks/bcl/include \
-    -I$rootdir/common/beerocks/bwl/include"
+INCLUDES=()
+while IFS='' read -r line; do INCLUDES+=("-I$line"); done < <(find -L "$rootdir/common" "$rootdir/framework" -type d -name include)
```
Comment (rmelotte) [inline tools/docker/static-analysis/cppcheck.sh:11]: Nice! We're less likely to forget to add new includes over time (or to remove old ones)...

**Review by rmelotte — APPROVED** [review]
Please double-check `pgrep` is available on every platform that use `platform_daemon.sh`.
Other than that only nitpicks :+1: .

File: framework/platform/bpl/uci/scripts/platform_daemon.sh (hunk 2 above)
Comment (ghost) [reply framework/platform/bpl/uci/scripts/platform_daemon.sh:57]: In fact, if `pgrep` is available, so will be `pkill` since they're both part of `procps`.
I see no reason to use `pgrep something | xargs kill` over `pkill something`.

Comment (rmelotte) [reply framework/platform/bpl/uci/scripts/platform_daemon.sh:57]: > In fact, if pgrep is available, so will be pkill since they're both part of procps.

Not necessarily. At the moment on the rax40 for example, Busybox has a variant of pgrep, but no pkill at all.

File: framework/platform/bpl/uci/scripts/platform_daemon.sh (hunk 1 above)
Comment (MuteSpirit) [reply framework/platform/bpl/uci/scripts/platform_daemon.sh:26]: I've checked that `pgrep` is present on RAX40 board.
     And absent `pkill` because otherwise i'd use it instead of.
I can check `pgrep` presence in built images for another platforms.

File: framework/platform/bpl/uci/scripts/platform_daemon.sh (hunk 2 above)
Comment (tomereli) [reply framework/platform/bpl/uci/scripts/platform_daemon.sh:57]: This we can change - we decide what to have in the RAX40 busybox configuration, I added history for example. John has no problem that we add more capabilities to prplWrt.

File: framework/platform/bpl/uci/scripts/platform_daemon.sh (hunk 1 above)
Comment (adam1985d) [reply framework/platform/bpl/uci/scripts/platform_daemon.sh:26]: I've verified existence of `pgrep` on the UGW and RDKB platforms
`pkill` on the other hand exists in RDKB but not in UGW
@tomereli @kantera800

File: framework/platform/bpl/uci/scripts/platform_daemon.sh (hunk 2 above)
Comment (adam1985d) [reply framework/platform/bpl/uci/scripts/platform_daemon.sh:57]: see my reply at:
https://github.com/prplfoundation/prplMesh/pull/1133#discussion_r409283040

File: framework/platform/bpl/uci/scripts/platform_daemon.sh (hunk 1 above)
Comment (tomereli) [reply framework/platform/bpl/uci/scripts/platform_daemon.sh:26]: In this case (UGW is much harder to change since it is a real product) - lets not use `pkill`.

Comment (MuteSpirit) [reply framework/platform/bpl/uci/scripts/platform_daemon.sh:26]: I've checked that `pgrep` is present in nightly build images for `turris-omnia` and `netgear-rax40`.
Also checked that config option `CONFIG_BUSYBOX_DEFAULT_PGREP=y` is present in `.config` OpenWrt file for device `glinet-b1300`.

So using `pgrep` looks reasonable

**Review by adam1985d — APPROVED** [review]
