### PR TITLE
Bugfix: fix topology response message 

### LINKED ISSUE #723: [BUG] Certification tests MAP-5.4.3 fail in CI (all variants)
The controller certification tests MAP-5.4.3 (all variants) fail in CI.

Logs are available here: https://gitlab.com/prpl-foundation/prplMesh/-/jobs/410892921/artifacts/browse/logs/FAIL/

The last UCC message for the FH24G was:
```
        ~~~~~ 4.1.1 Step 9 sniffer checks - Topology Response message ~~~~~

2020-01-22 03:15:24.755 - INFO - SNIFFER (192.168.250.5:9999) ---> sniffer_control_filter_capture,InFile,_MAP-4.1.1-STEP9,OutFile,MAP-4.1.1-STEP9,msgId,0x8001,filterfile,mapfile,msgType,0x0003,nframes,1
2020-01-22 03:15:25.217 - INFO - SNIFFER (192.168.250.5:9999) <-- status,COMPLETE,FilterStatus,NoPacketsFound,FrameCount,0

2020-01-22 03:15:25.226 - INFO - MSG: No Topology Response message found
2020-01-22 03:15:25.226 - INFO - 
```

### PR DESCRIPTION
**Pull request by CoralMalachi**
### Bug description 

Currently, test 5.4.3 keeps on failing with the master version (Marvell CTT Agent 1, prplMesh DUT) with the following error: 

image

### Reason
After exploring the root cause of this bug, it turned out that our topology response message did not match the IEEE_1905 document requirements. According to the IEEE_1905 document, section 6.4.5, the 1905 topology response message must include **One device information type TLV** (which currently is not added to the CMDU).

So when the Marvell sends a Topology Query to the prplMesh Controller, the prplMesh responds with a wrong topology response, which leads the Marvell agent to not respond to the controller Topology Query later when is triggered to.

Therefore, the required TLV is added to the Topology Response Message.
The rest of the fields of the TLV will be completed as part of the Supported Services Discovery task (#300).

Fixes #723
### Testbed status
_Test 5.4.3 passed._

Signed-off-by: Coral Malachi <coral.malachi@intel.com>

### CODE REVIEW

File: agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.cpp [hunk 1]
```diff
@@ -1766,6 +1767,17 @@ bool backhaul_manager::handle_1905_discovery_query(ieee1905_1::CmduMessageRx &cm
...
+    auto tlvDeviceInformation = cmdu_tx.addClass<ieee1905_1::tlvDeviceInformation>();
+    if (!tlvDeviceInformation) {
+        LOG(ERROR) << "addClass ieee1905_1::tlvDeviceInformation failed, mid=" << std::hex
+                   << (int)mid;
+        return false;
+    }
+    tlvDeviceInformation->mac() = network_utils::mac_from_string(bridge_info.mac);
+
+    //TODO: set number of local interfaces.
+    //TODO: fill info of each of the local interfaces, according to IEEE_1905 section 6.4.5
```
Comment (tomereli) [inline agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.cpp:1780]: Please add a link to the github issue - https://github.com/prplfoundation/prplMesh/issues/300

**Review by tomereli — APPROVED** [review]

**Review by rmelotte — APPROVED** [review]
